from entidades.usuarios_model import Usuarios
from entidades.configuracao_model import Configuracao
from entidades.humor_diario_model import HumorDiario
from entidades.task_informe_humor import TaskInformeHumor